package webhook

import (
	"bytes"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

// The vector file is the durable half of this package. It is generated by
// testdata/generate_vectors.py from the server's own signing code, NOT from
// anything in this package, so it is the only thing here that can catch this
// package agreeing with itself. Every test below that needs a known-good
// signature takes it from there rather than computing one.
const vectorsPath = "testdata/signature_vectors.json"

type signatureVectors struct {
	Comment   string            `json:"$comment"`
	Version   int               `json:"version"`
	Algorithm string            `json:"algorithm"`
	Header    string            `json:"header"`
	Format    string            `json:"format"`
	Encoding  map[string]string `json:"encoding"`
	Accept    []signatureVector `json:"accept"`
	Reject    []signatureVector `json:"reject"`
}

type signatureVector struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Secret      string `json:"secret"`
	// Body and BodyBase64 are pointers because "absent" and "the empty string"
	// are different vectors here: the empty-body cases carry "body": "".
	Body       *string `json:"body"`
	BodyBase64 *string `json:"body_base64"`
	Signature  string  `json:"signature"`
	Reason     string  `json:"reason"`
}

// bytes returns the vector's body. HMAC is over bytes, so a vector may carry a
// body that is not valid UTF-8 and therefore cannot be a JSON string.
func (v signatureVector) bytes() ([]byte, error) {
	switch {
	case v.Body != nil && v.BodyBase64 != nil:
		return nil, errors.New("vector sets both body and body_base64")
	case v.Body != nil:
		return []byte(*v.Body), nil
	case v.BodyBase64 != nil:
		decoded, err := base64.StdEncoding.DecodeString(*v.BodyBase64)
		if err != nil {
			return nil, fmt.Errorf("body_base64 is not base64: %w", err)
		}
		return decoded, nil
	default:
		return nil, errors.New("vector sets neither body nor body_base64")
	}
}

// rejectReasons maps the vector file's language-neutral reason strings onto this
// SDK's errors. The file names a reason rather than a Go sentinel so an SDK in
// another language can drive the same vectors; this table is the Go binding.
var rejectReasons = map[string]error{
	"missing_header":        ErrMissingSignature,
	"unsupported_algorithm": ErrUnsupportedAlgorithm,
	"malformed_digest":      ErrMalformedSignature,
	"digest_mismatch":       ErrSignatureMismatch,
	"empty_body":            ErrEmptyBody,
	"empty_secret":          ErrNoSecret,
}

func loadVectors(t *testing.T) signatureVectors {
	t.Helper()
	raw, err := os.ReadFile(vectorsPath)
	if err != nil {
		t.Fatalf("read %s: %v", vectorsPath, err)
	}
	var vectors signatureVectors
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&vectors); err != nil {
		// Unknown fields are rejected so a vector gaining a field the Go tests
		// ignore -- a per-vector flag, say -- fails here instead of being
		// silently skipped.
		t.Fatalf("decode %s: %v", vectorsPath, err)
	}
	return vectors
}

// TestSignatureVectorsAreUsable is the anti-vacuous-pass guard. Every other
// vector-driven test below iterates the file, and `for range nil` passes
// loudly-green: a truncated, emptied, or renamed vector file would turn this
// package's entire known-good suite into an assertion about nothing.
func TestSignatureVectorsAreUsable(t *testing.T) {
	vectors := loadVectors(t)

	if vectors.Version != 1 {
		t.Errorf("vector file version = %d, want 1 (the Go binding in this file was written for version 1)", vectors.Version)
	}
	if vectors.Algorithm != "HMAC-SHA256" {
		t.Errorf("algorithm = %q, want HMAC-SHA256", vectors.Algorithm)
	}
	if vectors.Header != HeaderSignature {
		t.Errorf("header = %q, want %q", vectors.Header, HeaderSignature)
	}
	// Floors, not exact counts: adding a vector must not require editing this.
	if len(vectors.Accept) < 8 {
		t.Errorf("accept vectors = %d, want at least 8", len(vectors.Accept))
	}
	if len(vectors.Reject) < 16 {
		t.Errorf("reject vectors = %d, want at least 16", len(vectors.Reject))
	}

	seen := map[string]bool{}
	for i, vector := range slices.Concat(vectors.Accept, vectors.Reject) {
		if vector.Name == "" {
			t.Errorf("vector %d has no name", i)
			continue
		}
		if seen[vector.Name] {
			t.Errorf("vector %q appears twice; names are how a failure is identified", vector.Name)
		}
		seen[vector.Name] = true
		if vector.Description == "" {
			t.Errorf("vector %q has no description; a vector nobody can explain is one nobody can port", vector.Name)
		}
		if _, err := vector.bytes(); err != nil {
			t.Errorf("vector %q: %v", vector.Name, err)
		}
	}

	for _, vector := range vectors.Accept {
		if vector.Reason != "" {
			t.Errorf("accept vector %q carries reason %q; reasons belong to reject vectors", vector.Name, vector.Reason)
		}
		if !strings.HasPrefix(vector.Signature, signaturePrefix) {
			t.Errorf("accept vector %q signature %q lacks the %q prefix", vector.Name, vector.Signature, signaturePrefix)
		}
	}

	// Every error this package can return has to be reachable from the shared
	// file, so a new refusal cannot be added without a portable vector proving
	// what triggers it.
	exercised := map[error]bool{}
	for _, vector := range vectors.Reject {
		want, ok := rejectReasons[vector.Reason]
		if !ok {
			t.Errorf("reject vector %q has unknown reason %q; add it to rejectReasons", vector.Name, vector.Reason)
			continue
		}
		exercised[want] = true
	}
	for reason, want := range rejectReasons {
		if !exercised[want] {
			t.Errorf("no reject vector carries reason %q, so %v is proved by nothing portable", reason, want)
		}
	}
}

func TestVerifyAcceptsKnownGoodVectors(t *testing.T) {
	for _, vector := range loadVectors(t).Accept {
		t.Run(vector.Name, func(t *testing.T) {
			body, err := vector.bytes()
			if err != nil {
				t.Fatalf("vector body: %v", err)
			}
			if err := Verify(vector.Secret, vector.Signature, body); err != nil {
				t.Fatalf("Verify() = %v, want nil\n%s", err, vector.Description)
			}
		})
	}
}

func TestVerifyRejectsKnownBadVectors(t *testing.T) {
	for _, vector := range loadVectors(t).Reject {
		t.Run(vector.Name, func(t *testing.T) {
			body, err := vector.bytes()
			if err != nil {
				t.Fatalf("vector body: %v", err)
			}
			want := rejectReasons[vector.Reason]
			got := Verify(vector.Secret, vector.Signature, body)
			if got == nil {
				t.Fatalf("Verify() = nil, want %v -- THIS VECTOR MUST NEVER VERIFY\n%s", want, vector.Description)
			}
			if !errors.Is(got, want) {
				t.Fatalf("Verify() = %v, want an error matching %v (reason %q)\n%s", got, want, vector.Reason, vector.Description)
			}
		})
	}
}

// sign is the server's signature, recomputed. It anchors the mutation tests
// below, which need a fresh known-good pair for a body the vector file does not
// contain. It is deliberately NOT used to produce any known-good expectation --
// that would only prove this package agrees with itself -- and it is checked
// against the vector file here before anything relies on it.
func sign(secret string, body []byte) string {
	mac := hmac.New(sha256.New, []byte(secret))
	mac.Write(body)
	return signaturePrefix + hex.EncodeToString(mac.Sum(nil))
}

func TestSignHelperMatchesTheVectorFile(t *testing.T) {
	for _, vector := range loadVectors(t).Accept {
		body, err := vector.bytes()
		if err != nil {
			t.Fatalf("vector %q body: %v", vector.Name, err)
		}
		if got := sign(vector.Secret, body); got != vector.Signature {
			t.Errorf("sign(%q) = %s, want %s", vector.Name, got, vector.Signature)
		}
	}
}

// TestVerifyRejectsEveryMutationOfASignedBody is the property the package
// exists for: the signature covers the bytes, all of them, exactly.
func TestVerifyRejectsEveryMutationOfASignedBody(t *testing.T) {
	const secret = "whsec_3f8a1c0d9b2e4f6a8c1d3e5f7a9b0c2d"
	body := []byte(`{"id":"0f1d7b24-2c1e-4f9a-9f3a-3a5f1c2d6e77","event_type":"tag.created"}`)
	signature := sign(secret, body)

	if err := Verify(secret, signature, body); err != nil {
		t.Fatalf("the unmutated body must verify first, or nothing below means anything: %v", err)
	}

	for i := range body {
		for _, mask := range []byte{0x01, 0x20, 0x80} {
			mutated := slices.Clone(body)
			mutated[i] ^= mask
			if err := Verify(secret, signature, mutated); !errors.Is(err, ErrSignatureMismatch) {
				t.Fatalf("body[%d] ^= %#x: Verify() = %v, want ErrSignatureMismatch", i, mask, err)
			}
		}
	}

	// Truncation at every length, which is the shape a partially-read stream
	// hands the verifier. Length 0 is ErrEmptyBody and is covered by the
	// vectors; every non-empty prefix is a mismatch.
	for n := 1; n < len(body); n++ {
		if err := Verify(secret, signature, body[:n]); !errors.Is(err, ErrSignatureMismatch) {
			t.Fatalf("body[:%d]: Verify() = %v, want ErrSignatureMismatch", n, err)
		}
	}

	for _, suffix := range []string{"\n", " ", "\x00", "{}"} {
		extended := append(slices.Clone(body), suffix...)
		if err := Verify(secret, signature, extended); !errors.Is(err, ErrSignatureMismatch) {
			t.Fatalf("body+%q: Verify() = %v, want ErrSignatureMismatch", suffix, err)
		}
	}

	// A different secret over the same bytes, which is what an attacker who
	// cannot read the signing secret can actually produce.
	if err := Verify(secret+"x", signature, body); !errors.Is(err, ErrSignatureMismatch) {
		t.Fatalf("wrong secret: Verify() = %v, want ErrSignatureMismatch", err)
	}
}

func TestVerifyRejectsMalformedHeaders(t *testing.T) {
	const secret = "whsec_3f8a1c0d9b2e4f6a8c1d3e5f7a9b0c2d"
	body := []byte(`{"event_type":"tag.created"}`)
	valid := strings.TrimPrefix(sign(secret, body), signaturePrefix)

	tests := []struct {
		name      string
		signature string
		want      error
	}{
		{"empty", "", ErrMissingSignature},
		{"whitespace only", "   ", ErrUnsupportedAlgorithm},
		{"no prefix", valid, ErrUnsupportedAlgorithm},
		{"uppercase prefix", "SHA256=" + valid, ErrUnsupportedAlgorithm},
		{"mixed case prefix", "Sha256=" + valid, ErrUnsupportedAlgorithm},
		{"other algorithm", "sha512=" + valid, ErrUnsupportedAlgorithm},
		{"prefix without separator", "sha256" + valid, ErrUnsupportedAlgorithm},
		{"leading space before prefix", " " + signaturePrefix + valid, ErrUnsupportedAlgorithm},
		{"double prefix", signaturePrefix + signaturePrefix + valid, ErrMalformedSignature},
		{"prefix only", signaturePrefix, ErrMalformedSignature},
		{"one char short", signaturePrefix + valid[:len(valid)-1], ErrMalformedSignature},
		{"one char long", signaturePrefix + valid + "a", ErrMalformedSignature},
		// Even lengths decode cleanly as hex, so only an explicit length check
		// tells these from a mismatch -- and a comparison that stops at the
		// shorter value would accept the first one outright.
		{"two chars short", signaturePrefix + valid[:len(valid)-2], ErrMalformedSignature},
		{"two chars long", signaturePrefix + valid + "ab", ErrMalformedSignature},
		{"non-hex", signaturePrefix + strings.Repeat("z", 64), ErrMalformedSignature},
		{"non-hex unicode", signaturePrefix + strings.Repeat("é", 32), ErrMalformedSignature},
		{"trailing space", signaturePrefix + valid + " ", ErrMalformedSignature},
		{"comma separated list", signaturePrefix + valid + "," + signaturePrefix + valid, ErrMalformedSignature},
		{"digest of nothing", signaturePrefix + strings.Repeat("0", 64), ErrSignatureMismatch},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			err := Verify(secret, test.signature, body)
			if err == nil {
				t.Fatalf("Verify() = nil, want %v", test.want)
			}
			if !errors.Is(err, test.want) {
				t.Fatalf("Verify() = %v, want an error matching %v", err, test.want)
			}
		})
	}
}

func TestVerifyRejectsCallerMistakes(t *testing.T) {
	const secret = "whsec_3f8a1c0d9b2e4f6a8c1d3e5f7a9b0c2d"
	body := []byte(`{"event_type":"tag.created"}`)
	signature := sign(secret, body)

	t.Run("empty secret with an otherwise valid delivery", func(t *testing.T) {
		// The signature below IS correct for the empty key. Verifying it would
		// be verifying against a key every attacker also has.
		if err := Verify("", sign("", body), body); !errors.Is(err, ErrNoSecret) {
			t.Fatalf("Verify() = %v, want ErrNoSecret", err)
		}
	})

	t.Run("nil body", func(t *testing.T) {
		if err := Verify(secret, signature, nil); !errors.Is(err, ErrEmptyBody) {
			t.Fatalf("Verify() = %v, want ErrEmptyBody", err)
		}
	})

	t.Run("drained body", func(t *testing.T) {
		if err := Verify(secret, signature, []byte{}); !errors.Is(err, ErrEmptyBody) {
			t.Fatalf("Verify() = %v, want ErrEmptyBody", err)
		}
	})

	t.Run("empty body with its own correct digest", func(t *testing.T) {
		// Cryptographically valid, refused as policy: Octonomy never sends an
		// empty body, so this is a drained stream that happened to be signed.
		if err := Verify(secret, sign(secret, nil), nil); !errors.Is(err, ErrEmptyBody) {
			t.Fatalf("Verify() = %v, want ErrEmptyBody", err)
		}
	})
}

// TestVerifyErrorsAreMutuallyDistinguishable backs the issue's requirement that
// no failure can be mistaken for another -- or for success. errors.Is on a
// sentinel is only useful if the sentinels do not match each other.
func TestVerifyErrorsAreMutuallyDistinguishable(t *testing.T) {
	all := map[string]error{
		"ErrNoSecret":             ErrNoSecret,
		"ErrMissingSignature":     ErrMissingSignature,
		"ErrUnsupportedAlgorithm": ErrUnsupportedAlgorithm,
		"ErrMalformedSignature":   ErrMalformedSignature,
		"ErrSignatureMismatch":    ErrSignatureMismatch,
		"ErrEmptyBody":            ErrEmptyBody,
	}
	for name, err := range all {
		if err == nil {
			t.Fatalf("%s is nil", name)
		}
		if !strings.HasPrefix(err.Error(), "octonomy: webhook ") {
			t.Errorf("%s message %q does not carry the SDK's error prefix", name, err.Error())
		}
		for otherName, other := range all {
			if name == otherName {
				continue
			}
			if errors.Is(err, other) {
				t.Errorf("errors.Is(%s, %s) is true; the two refusals are not distinguishable", name, otherName)
			}
		}
	}
}

// TestVerifyAcceptsUppercaseHexDigest is the behavioral half of the
// constant-time requirement. An implementation that compared the hex TEXT --
// `receivedHex == expectedHex` -- rejects this; one that decodes and compares
// the bytes accepts it. So this passing is evidence the comparison is not a
// string comparison, which no functional test of correct signatures can show.
func TestVerifyAcceptsUppercaseHexDigest(t *testing.T) {
	vectors := loadVectors(t)
	if len(vectors.Accept) == 0 {
		t.Fatal("no accept vectors")
	}
	for _, vector := range vectors.Accept {
		body, err := vector.bytes()
		if err != nil {
			t.Fatalf("vector %q body: %v", vector.Name, err)
		}
		upper := signaturePrefix + strings.ToUpper(strings.TrimPrefix(vector.Signature, signaturePrefix))
		if upper == vector.Signature {
			t.Fatalf("vector %q signature has no lowercase hex to upcase", vector.Name)
		}
		if err := Verify(vector.Secret, upper, body); err != nil {
			t.Errorf("vector %q with an uppercase digest: Verify() = %v, want nil", vector.Name, err)
		}
	}
}

// TestVerifyComparesDigestsInConstantTime is the issue's review checklist item,
// turned into something that fails a build instead of relying on a reviewer
// noticing. `==` and bytes.Equal on digests pass every functional test in this
// file -- correct signatures still verify and forged ones are still refused --
// while leaking, byte by byte, how far a forgery got. The defect is invisible
// to behavior, so it is checked in the source.
func TestVerifyComparesDigestsInConstantTime(t *testing.T) {
	const source = "verify.go"
	file, err := parser.ParseFile(token.NewFileSet(), source, nil, 0)
	if err != nil {
		t.Fatalf("parse %s: %v", source, err)
	}

	// Comparisons that are byte-correct but not constant-time. hmac.Equal is
	// the only one allowed to touch a digest.
	banned := map[string]string{
		"bytes.Equal":                "byte-wise but not constant-time",
		"bytes.Compare":              "byte-wise but not constant-time",
		"bytes.HasPrefix":            "a prefix match is not a digest comparison",
		"strings.Compare":            "compares the hex text, not the digest",
		"strings.EqualFold":          "compares the hex text, not the digest",
		"reflect.DeepEqual":          "not constant-time",
		"slices.Equal":               "not constant-time",
		"subtle.ConstantTimeCompare": "constant-time, but hmac.Equal is the documented spelling here and is what the vectors' guarantee is written against",
	}

	var (
		usesHMACEqual bool
		comparisons   []*ast.BinaryExpr
	)
	ast.Inspect(file, func(node ast.Node) bool {
		switch typed := node.(type) {
		case *ast.CallExpr:
			selector, ok := typed.Fun.(*ast.SelectorExpr)
			if !ok {
				return true
			}
			pkg, ok := selector.X.(*ast.Ident)
			if !ok {
				return true
			}
			name := pkg.Name + "." + selector.Sel.Name
			if name == "hmac.Equal" {
				usesHMACEqual = true
			}
			if why, forbidden := banned[name]; forbidden {
				t.Errorf("%s calls %s: %s", source, name, why)
			}
		case *ast.BinaryExpr:
			if typed.Op == token.EQL || typed.Op == token.NEQ {
				comparisons = append(comparisons, typed)
			}
		}
		return true
	})

	if !usesHMACEqual {
		t.Errorf("%s does not call hmac.Equal; digests must be compared in constant time", source)
	}

	// Nothing derived from a digest may reach an == or != at all. The guarded
	// spellings track verify.go: `received` is the decoded header digest and
	// `.Sum(` produces the computed one.
	guarded := []string{"received", ".Sum("}
	if body := string(mustReadFile(t, source)); !strings.Contains(body, "received") || !strings.Contains(body, ".Sum(") {
		t.Fatalf("%s no longer mentions %v -- the digest values were renamed, so this test is now guarding nothing. Update `guarded`.", source, guarded)
	}
	for _, comparison := range comparisons {
		text := types.ExprString(comparison)
		for _, needle := range guarded {
			if strings.Contains(text, needle) {
				t.Errorf("%s compares a digest with %s: %q -- use hmac.Equal", source, comparison.Op, text)
			}
		}
	}
}

func mustReadFile(t *testing.T, name string) []byte {
	t.Helper()
	content, err := os.ReadFile(filepath.Clean(name))
	if err != nil {
		t.Fatalf("read %s: %v", name, err)
	}
	return content
}

// FuzzVerify asserts the two things that must hold for every input: Verify
// never panics on one, and a body signed with a secret always verifies under
// that secret. The second is what stops a "harden it" patch from tightening the
// parser until real deliveries stop verifying.
func FuzzVerify(f *testing.F) {
	vectors := signatureVectors{}
	if raw, err := os.ReadFile(vectorsPath); err == nil {
		_ = json.Unmarshal(raw, &vectors)
	}
	for _, vector := range slices.Concat(vectors.Accept, vectors.Reject) {
		if body, err := vector.bytes(); err == nil {
			f.Add(vector.Secret, vector.Signature, body)
		}
	}
	f.Add("", "", []byte(nil))
	f.Add("secret", "sha256=", []byte("{}"))

	f.Fuzz(func(t *testing.T, secret, signature string, body []byte) {
		err := Verify(secret, signature, body)
		if err == nil && (secret == "" || len(body) == 0) {
			t.Fatalf("Verify() accepted a delivery with secret=%q and a %d-byte body", secret, len(body))
		}
		if secret == "" || len(body) == 0 {
			return
		}
		if err := Verify(secret, sign(secret, body), body); err != nil {
			t.Fatalf("a body signed with its own secret failed to verify: %v", err)
		}
	})
}
