#!/usr/bin/env python3
"""Regenerate signature_vectors.json.

The digests in signature_vectors.json are NOT produced by the Go code they
test. They are produced here, by the same three lines the Octonomy server runs
in octonomy/events/dispatch.py::_webhook_signature:

    digest = hmac.new(signing_secret.encode("utf-8"), body, hashlib.sha256).hexdigest()
    return f"sha256={digest}"

That independence is the point. A vector computed by the implementation under
test proves only that the implementation agrees with itself; these agree with
the emitter.

Usage:  python3 generate_vectors.py > signature_vectors.json
"""

import base64
import hashlib
import hmac
import json
import sys


def sign(secret: str, body: bytes) -> str:
    """Byte-for-byte the server's _webhook_signature."""
    digest = hmac.new(secret.encode("utf-8"), body, hashlib.sha256).hexdigest()
    return f"sha256={digest}"


def envelope(**overrides) -> bytes:
    """A serialized outbox event, exactly as the server puts it on the wire.

    Mirrors serialize_outbox_event() followed by the json.dumps call in
    WebhookEventTransport.publish: compact separators, sorted keys, UTF-8.
    Reproduced here so a vector body is a REAL payload shape, not a toy one --
    a consumer that only ever verified {"hello":"world"} has not verified the
    thing it will actually receive.
    """
    event = {
        "id": "0f1d7b24-2c1e-4f9a-9f3a-3a5f1c2d6e77",
        "tenant_id": "acme",
        "application_id": "storefront",
        "namespace_type": None,
        "namespace_id": None,
        "event_type": "tag.created",
        "aggregate_type": "tag",
        "aggregate_id": "9c2b0f41-5d33-4a6f-8b17-2e4c9a7d0b55",
        "operation_id": "5f0a3d18-7b62-4c19-9e84-1d6b8f2a4c30",
        "request_id": None,
        "actor_id": "user_42",
        "tag_id": "9c2b0f41-5d33-4a6f-8b17-2e4c9a7d0b55",
        "resource_type": None,
        "resource_id": None,
        "payload": {
            "after": {
                "id": "9c2b0f41-5d33-4a6f-8b17-2e4c9a7d0b55",
                "slug": "summer-sale",
                "name": "Summer Sale",
                "is_active": True,
                "vocabulary_id": "3b7e5a90-1c48-4d2b-a6f5-8e0d9c1b4a26",
            }
        },
        "metadata": {"source": "api"},
    }
    event.update(overrides)
    return json.dumps(
        event, default=str, separators=(",", ":"), sort_keys=True
    ).encode("utf-8")


SECRET = "whsec_3f8a1c0d9b2e4f6a8c1d3e5f7a9b0c2d"
ROTATED_SECRET = "whsec_0a1b2c3d4e5f60718293a4b5c6d7e8f90"
UNICODE_SECRET = "clé-secrète-Ω-日本語"

GLOBAL_EVENT = envelope()
MERCHANT_EVENT = envelope(
    id="7a3c9e15-8b40-4d27-9f61-0c5e2a8d3b19",
    namespace_type="merchant",
    namespace_id="merchant-9931",
    event_type="tag.updated",
    request_id="req_2f9c7b1a-6d38-4e05-b7a2-9c1e4f8d60a3",
    payload={"before": {"name": "Summer Sale"}, "after": {"name": "Summer Clearance"}},
)
ASCII_BODY = b'{"id":"0f1d7b24-2c1e-4f9a-9f3a-3a5f1c2d6e77","event_type":"tag.created"}'
UNICODE_BODY = '{"name":"Café Ω 日本語 \U0001f3f7"}'.encode("utf-8")
BINARY_BODY = bytes([0x00, 0x01, 0xFF, 0xFE, 0x7F, 0x80, 0x0A, 0x0D])


def accept(name, description, secret, body):
    vector = {"name": name, "description": description, "secret": secret}
    try:
        vector["body"] = body.decode("utf-8")
    except UnicodeDecodeError:
        # HMAC is over BYTES. A body that is not valid UTF-8 still has to
        # verify, so the format carries a base64 alternative rather than
        # pretending every payload is text.
        vector["body_base64"] = base64.b64encode(body).decode("ascii")
    vector["signature"] = sign(secret, body)
    return vector


def reject(name, description, secret, body, signature, reason):
    vector = {"name": name, "description": description, "secret": secret}
    try:
        vector["body"] = body.decode("utf-8")
    except UnicodeDecodeError:
        vector["body_base64"] = base64.b64encode(body).decode("ascii")
    vector["signature"] = signature
    vector["reason"] = reason
    return vector


VALID_DIGEST = sign(SECRET, ASCII_BODY).removeprefix("sha256=")

document = {
    "$comment": (
        "Known-good HMAC-SHA256 signature vectors for Octonomy webhook "
        "deliveries. Generated by generate_vectors.py, which mirrors the "
        "server's octonomy/events/dispatch.py::_webhook_signature. Portable "
        "across SDKs -- see README.md in this directory."
    ),
    "version": 1,
    "algorithm": "HMAC-SHA256",
    "header": "X-Octonomy-Signature",
    "format": "sha256=<lowercase hex digest of HMAC-SHA256(utf8(secret), raw_body)>",
    "encoding": {
        "secret": "UTF-8 text, encoded to bytes before use as the HMAC key",
        "body": "UTF-8 text; when a vector carries body_base64 instead, the body is those base64-decoded BYTES",
    },
    "accept": [
        accept(
            "global-tag-created-envelope",
            "A real tag.created outbox envelope for the global (tenant-shared) namespace, serialized the way the server serializes it: compact separators, sorted keys, UTF-8.",
            SECRET,
            GLOBAL_EVENT,
        ),
        accept(
            "merchant-tag-updated-envelope",
            "A merchant-namespaced tag.updated envelope carrying a request_id. *.updated payloads hold only the CHANGED fields, not a full snapshot.",
            SECRET,
            MERCHANT_EVENT,
        ),
        accept(
            "rotated-secret",
            "The global envelope signed with a second secret. During rotation a consumer must accept a body signed by EITHER secret, so the same body appears here under both.",
            ROTATED_SECRET,
            GLOBAL_EVENT,
        ),
        accept(
            "minimal-ascii-body",
            "A short all-ASCII body. The floor case: if this one fails, nothing else will pass either.",
            SECRET,
            ASCII_BODY,
        ),
        accept(
            "utf8-body",
            "A body with multi-byte UTF-8: accented Latin, Greek, CJK, and an emoji outside the BMP. Signing the decoded string instead of its bytes fails here.",
            SECRET,
            UNICODE_BODY,
        ),
        accept(
            "utf8-secret",
            "A secret that is itself multi-byte UTF-8. The key is utf8(secret), not its code points.",
            UNICODE_SECRET,
            ASCII_BODY,
        ),
        accept(
            "trailing-newline-body",
            "The minimal ASCII body plus one trailing newline -- a different signature. Any implementation that trims, re-serializes, or 'tidies' the body before hashing produces the minimal-ascii-body digest here and is wrong.",
            SECRET,
            ASCII_BODY + b"\n",
        ),
        accept(
            "non-utf8-binary-body",
            "A body that is not valid UTF-8 at all (carried as body_base64). HMAC is over bytes; a string-typed body parameter cannot express this case.",
            SECRET,
            BINARY_BODY,
        ),
    ],
    "reject": [
        reject(
            "missing-header",
            "No X-Octonomy-Signature header at all -- an unsigned POST to the webhook endpoint.",
            SECRET,
            ASCII_BODY,
            "",
            "missing_header",
        ),
        reject(
            "bare-hex-no-prefix",
            "The correct digest with the sha256= prefix stripped. Correct bytes, wrong grammar.",
            SECRET,
            ASCII_BODY,
            VALID_DIGEST,
            "unsupported_algorithm",
        ),
        reject(
            "uppercase-prefix",
            "SHA256= rather than sha256=. The server emits lowercase; the prefix is matched exactly.",
            SECRET,
            ASCII_BODY,
            "SHA256=" + VALID_DIGEST,
            "unsupported_algorithm",
        ),
        reject(
            "sha512-prefix",
            "A digest announced as a different algorithm. Accepting it would let a sender choose the algorithm.",
            SECRET,
            ASCII_BODY,
            "sha512=" + VALID_DIGEST,
            "unsupported_algorithm",
        ),
        reject(
            "non-hex-digest",
            "Sixty-four characters that are not hexadecimal.",
            SECRET,
            ASCII_BODY,
            "sha256=" + "z" * 64,
            "malformed_digest",
        ),
        reject(
            "short-digest",
            "A hex digest one character short of SHA-256's 64. A length-blind comparison can read this as a prefix match.",
            SECRET,
            ASCII_BODY,
            "sha256=" + VALID_DIGEST[:-1],
            "malformed_digest",
        ),
        reject(
            "even-length-short-digest",
            "The correct digest with its last TWO characters removed: still valid hex, still decodable, still the wrong length. An implementation that leaves length to the comparison reports this as a mismatch rather than as malformed -- and one that compares only as far as the shorter value accepts it outright.",
            SECRET,
            ASCII_BODY,
            "sha256=" + VALID_DIGEST[:-2],
            "malformed_digest",
        ),
        reject(
            "even-length-long-digest",
            "The correct digest with two extra hex characters appended -- decodable, and 33 bytes where 32 are required.",
            SECRET,
            ASCII_BODY,
            "sha256=" + VALID_DIGEST + "ab",
            "malformed_digest",
        ),
        reject(
            "long-digest",
            "The correct digest with an extra hex character appended.",
            SECRET,
            ASCII_BODY,
            "sha256=" + VALID_DIGEST + "a",
            "malformed_digest",
        ),
        reject(
            "empty-digest",
            "The prefix with nothing after it.",
            SECRET,
            ASCII_BODY,
            "sha256=",
            "malformed_digest",
        ),
        reject(
            "wrong-secret",
            "A well-formed digest of this exact body under a DIFFERENT secret -- what an attacker who cannot read the signing secret produces.",
            SECRET,
            ASCII_BODY,
            sign(ROTATED_SECRET, ASCII_BODY),
            "digest_mismatch",
        ),
        reject(
            "body-mutated-after-signing",
            "The signature is genuine for the original envelope; the body has had one field value changed since. This is the whole reason verification exists.",
            SECRET,
            GLOBAL_EVENT.replace(b'"tenant_id":"acme"', b'"tenant_id":"evil"'),
            sign(SECRET, GLOBAL_EVENT),
            "digest_mismatch",
        ),
        reject(
            "truncated-body",
            "A genuine signature over the full envelope, presented with a body cut short -- what a size-capped or partially-read stream hands the verifier.",
            SECRET,
            GLOBAL_EVENT[: len(GLOBAL_EVENT) // 2],
            sign(SECRET, GLOBAL_EVENT),
            "digest_mismatch",
        ),
        reject(
            "empty-body-consumed-stream",
            "A genuine signature over the full envelope, presented with zero bytes -- what a verifier gets when middleware, a logger, or a JSON decoder drained the request body first.",
            SECRET,
            b"",
            sign(SECRET, GLOBAL_EVENT),
            "empty_body",
        ),
        reject(
            "empty-body-correct-digest",
            "Zero bytes together with their OWN correct digest. Cryptographically this pair is valid -- HMAC of the empty message is well defined -- and it is recorded here so an SDK that chooses to accept empty bodies has the digest. octonomy-go refuses it: the Octonomy server never emits an empty body, so the realistic cause is a drained stream, and 'empty_body' is therefore a POLICY reason rather than a cryptographic one. See README.md.",
            SECRET,
            b"",
            sign(SECRET, b""),
            "empty_body",
        ),
        reject(
            "empty-secret",
            "A correct digest under an EMPTY signing secret -- what an unset environment variable produces. The digest verifies, which is the danger: with no secret the key is public, so anyone can mint one. Refused as policy, like empty_body.",
            "",
            ASCII_BODY,
            sign("", ASCII_BODY),
            "empty_secret",
        ),
    ],
}

json.dump(document, sys.stdout, indent=2, ensure_ascii=False)
sys.stdout.write("\n")
