#!/bin/sh
# Release-line guard: assert go.mod still matches the line it sits on.
#
# Two halves, deliberately different severities.
#
# BLOCKING -- the `go` directive on the compat line. It is the one assertion with
# no toolchain backstop. A v1.x tag cut from support/go1.13 after the directive
# drifted to, say, `go 1.24` carries the SAME module path, so the proxy and the
# go command accept it, a Go 1.13 consumer resolves it inside their ordinary
# version range, and it does not compile for them. `retract` cannot reach them
# either: that directive shipped in Go 1.16, so their toolchain ignores it. The
# tag is permanent. This check is the only thing standing there.
#
# ADVISORY -- module path / branch consistency on a BRANCH or PR. Go rejects a
# path mismatch itself:
#
#   go: github.com/octoverse-id/octonomy-go@v1.0.0: invalid version:
#       go.mod has post-v1 module path ".../octonomy-go/v2" at revision v1.0.0
#
# so on a branch these are early signals, not gates. They warn and do not fail.
#
# BLOCKING AT TAG TIME -- the same checks stop being advisory the moment a tag is
# involved, because that is where permanence attaches. Go rejecting a bad tag
# afterwards does not help: the tag is already public and proxy-cached, and it
# cannot be withdrawn for a Go 1.13 consumer. So on a tag push this script
# asserts the tag against the module path AND against version.go, which is the
# gap that let `refs/tags/v1.0.0` pass on a tree whose version.go read 0.1.0.
#
# Usage:
#   scripts/compat-guard.sh          # infers the line from git or $GITHUB_*
#
# POSIX sh. Utilities used: git, sed, grep -E, head. Nothing newer than the era
# this line targets, so it runs the same on an old box as on a current runner.

set -eu

# A literal newline, for the multi-line guard in is_semver.
_NL='
'

COMPAT_MODULE="github.com/octoverse-id/octonomy-go"
COMPAT_BRANCH="support/go1.13"
COMPAT_GO="1.13"
MODERN_BRANCH="main"

failed=0

note() {
	if [ "${GITHUB_ACTIONS:-}" = "true" ]; then printf '::notice::%s\n' "$1"; else printf 'note: %s\n' "$1"; fi
}
warn() {
	if [ "${GITHUB_ACTIONS:-}" = "true" ]; then printf '::warning::%s\n' "$1"; else printf 'ADVISORY: %s\n' "$1"; fi
}
fail() {
	if [ "${GITHUB_ACTIONS:-}" = "true" ]; then printf '::error::%s\n' "$1"; else printf 'BLOCKING: %s\n' "$1"; fi
	failed=1
}

# --- Version grammar ----------------------------------------------------------
#
# is_semver is a real grammar check, because a shell glob is not one: the obvious
# `v[0-9]*.[0-9]*.[0-9]*` pattern also accepts v1.2.3foo, v1.02.3 (leading zero),
# v1.2.3- (empty prerelease), and v1.2.3.4. Those are not module versions, and a
# guard that reports "valid SemVer" while accepting them is worse than no check.
#
# Build metadata (+meta) is rejected on purpose: SemVer allows it, Go module
# versions do not carry it (the sole exception, +incompatible, is generated by
# the toolchain, never tagged by hand).
is_semver() {
	# grep succeeds when ANY line matches, so a multi-line argument could smuggle
	# junk past a valid-looking line. Git refs cannot contain newlines, but
	# version.go is also fed through here and it is not a ref.
	case "$1" in
	*"$_NL"*) return 1 ;;
	esac
	# The prerelease part is the official grammar, not [0-9A-Za-z-]+: a numeric
	# prerelease identifier may not carry a leading zero, so 1.0.0-01 and
	# 1.0.0-alpha.01 are invalid SemVer even though a looser class accepts them.
	printf '%s' "$1" | grep -Eq '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(\.(0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*)?$'
}

# expected_module_path <major> echoes the one module path a release of that major
# may carry. Go forbids BOTH /v0 and /v1 suffixes (golang.org/x/mod/module:
# SplitPathVersion rejects them), so majors 0 and 1 are unsuffixed and 2+ append
# /vN. Getting v0 wrong mattered: version.go still reads 0.1.0, so a v0.x release
# branch is a plausible slip, and it would have been mapped to an illegal /v0.
expected_module_path() {
	case "$1" in
	0 | 1) printf '%s' "$COMPAT_MODULE" ;;
	*) printf '%s/v%s' "$COMPAT_MODULE" "$1" ;;
	esac
}

semver_major() {
	printf '%s' "$1" | sed -n 's/^\([0-9]\{1,\}\)\..*/\1/p'
}

# --- Read the tree -------------------------------------------------------------
#
# Leading whitespace is tolerated, and Version is read from both the single-line
# `const Version = "..."` and the grouped `const ( Version = "..." )` form, so a
# harmless reformat cannot quietly turn a blocking check into a skipped one.

test -f go.mod || { fail "no go.mod in $(pwd)"; exit 1; }

module=$(sed -n 's/^[[:space:]]*module[[:space:]]\{1,\}\([^[:space:]]*\).*/\1/p' go.mod | head -n 1)
go_directive=$(sed -n 's/^[[:space:]]*go[[:space:]]\{1,\}\([0-9][0-9.]*\).*/\1/p' go.mod | head -n 1)
version=$(sed -n 's/^[[:space:]]*const Version = "\([^"]*\)".*/\1/p;s/^[[:space:]]*Version = "\([^"]*\)".*/\1/p' version.go 2>/dev/null | head -n 1)

test -n "$module" || { fail "could not read the module path from go.mod"; exit 1; }
test -n "$go_directive" || { fail "could not read the go directive from go.mod"; exit 1; }

# The module path suffix is what makes the two lines different modules to Go.
# Any digit count: /v100 is a real major, and reading it as 1 would defeat the
# comparison it feeds. A non-numeric suffix (.../v2ray) is not a major at all.
path_major=1
case "$module" in
	*/v[0-9]*)
		_suffix=${module##*/v}
		case "$_suffix" in
			"" | *[!0-9]*) path_major=1 ;;
			*) path_major=$_suffix ;;
		esac
		;;
esac

# --- Work out which line this run belongs to -----------------------------------
#
# A PR is judged by its BASE branch, which is what puts this check on the
# release PR: a release/vX.Y.Z PR targets the line it will be tagged on. A
# tag-push-only check fires after the tag is already proxy-resolvable -- it
# would report a mistake nobody can undo.

tag=""
branch=""
head_branch="${GITHUB_HEAD_REF:-}"
case "${GITHUB_EVENT_NAME:-}" in
	pull_request | pull_request_target) branch="${GITHUB_BASE_REF:-}" ;;
	*)
		case "${GITHUB_REF:-}" in
			refs/tags/*) tag="${GITHUB_REF#refs/tags/}" ;;
			refs/heads/*) branch="${GITHUB_REF#refs/heads/}" ;;
			*) branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "") ;;
		esac
		;;
esac

# A release PR is where the version can still be corrected: docs/release.md cuts
# release/vX.Y.Z off the line, and the tag is pushed only after that PR merges.
# Everything asserted under is_release_pr is therefore a check that can still be
# acted on, which is the entire point -- see the tag-time block for why the same
# assertions arriving later are consolation and not a gate.
# Locally there is no GITHUB_HEAD_REF, so fall back to the checked-out branch.
# Without this, `make check` on a release branch silently skips every release
# assertion -- the guard would be at its most lenient exactly where a developer
# is most likely to be preparing the unrecallable thing.
if [ -z "$head_branch" ] && [ -z "$tag" ]; then
	head_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
fi

release_version=""
is_release_pr=0
case "$head_branch" in
	release/v*) release_version=${head_branch#release/v}; is_release_pr=1 ;;
	release/*) release_version=${head_branch#release/}; is_release_pr=1 ;;
esac

printf 'compat-guard: module=%s go=%s version=%s branch=%s head=%s tag=%s\n' \
	"$module" "$go_directive" "${version:-?}" "${branch:-none}" "${head_branch:-none}" "${tag:-none}"

# A tag push is the last gate before something permanent. Everything checked
# under `is_tag` below is blocking for that reason, including checks that only
# warn on a branch.
is_tag=0
[ -n "$tag" ] && is_tag=1

# --- BLOCKING: the go directive on the compat line -----------------------------
#
# Triggered by either independent signal -- the module path in the tree, or the
# branch context. Requiring both would let a change that rewrote go.mod's module
# line slip past on a technicality.

on_compat=0
[ "$module" = "$COMPAT_MODULE" ] && on_compat=1
[ "$branch" = "$COMPAT_BRANCH" ] && on_compat=1
case "$tag" in v1.*) on_compat=1 ;; esac

if [ "$on_compat" = "1" ]; then
	if [ "$go_directive" != "$COMPAT_GO" ]; then
		fail "the compat line must declare \`go $COMPAT_GO\` in go.mod, found \`go $go_directive\`. A v1.x release built on this go.mod keeps the same module path, so Go accepts it and a Go 1.13 consumer cannot compile it -- and \`retract\` (Go 1.16+) cannot reach that consumer. Fix go.mod, do not tag."
	else
		note "compat line: go.mod declares \`go $COMPAT_GO\` as required"
	fi
fi

# --- Path / branch consistency: advisory on a branch, blocking on a tag --------

if [ "$branch" = "$COMPAT_BRANCH" ] && [ "$module" != "$COMPAT_MODULE" ]; then
	warn "branch $COMPAT_BRANCH carries module path \`$module\`, expected the unsuffixed \`$COMPAT_MODULE\`. Go rejects the mismatch at resolve time, so on a branch this is a signal rather than the gate."
fi

# The converse direction, which was previously unchecked: the modern line must
# NOT be carrying the compat module or the 1.13 floor. This is how a cherry-pick
# from this branch to main -- go.mod included -- would show up.
if [ "$branch" = "$MODERN_BRANCH" ]; then
	if [ "$module" = "$COMPAT_MODULE" ]; then
		warn "branch $MODERN_BRANCH carries the unsuffixed compat module \`$module\`, expected a /vN-suffixed path. A compat-line go.mod reached the modern line, most likely via a cherry-pick that included it."
	fi
	if [ "$go_directive" = "$COMPAT_GO" ]; then
		warn "branch $MODERN_BRANCH declares \`go $COMPAT_GO\`, the compat floor. The modern line's floor is far higher; check what cherry-picked go.mod landed here."
	fi
fi

# --- BLOCKING on a release PR: the last point where a fix is still cheap -------
#
# The tag checks below run after `git push origin <tag>`, by which time the ref is
# public and proxy-fetchable; for this line that is unrecoverable. So the same
# assertions run here, on the release PR, where the answer is "push a commit"
# rather than "publish a corrected version and explain the gap".

if [ "$is_release_pr" = "1" ]; then
	if ! is_semver "$release_version"; then
		fail "release branch $head_branch does not name a valid version ($release_version). Expected release/vMAJOR.MINOR.PATCH with an optional -prerelease, per docs/release.md."
	else
		rel_major=$(semver_major "$release_version")
		if [ -z "$version" ]; then
			fail "release PR for v$release_version but version.go declares no Version. Nothing would tie the tag to the code it publishes."
		elif [ "$version" != "$release_version" ]; then
			fail "release PR for v$release_version but version.go says $version. Set Version to $release_version (docs/release.md step 3) -- once the tag is pushed this is no longer fixable."
		fi
		# The EXACT path, not merely a matching major. Comparing majors alone
		# accepts `module example.test/wrong` with `go 1.13` on a v1 release PR,
		# and accepts a `/v1` suffix that is not a legal Go module path at all --
		# both publish something no consumer of this line can resolve, and both
		# were passing with a warning.
		if [ "$rel_major" = "0" ]; then
			fail "release PR for v$release_version: this repository publishes v1.x on \`$COMPAT_BRANCH\` and v2.x on \`$MODERN_BRANCH\` (docs/versioning.md). No line publishes v0, and a v0 tag would claim the unstable-API contract both lines have moved past."
		fi
		rel_expected_module=$(expected_module_path "$rel_major")
		if [ "$module" != "$rel_expected_module" ]; then
			fail "release PR for v$release_version must carry module path \`$rel_expected_module\`, but go.mod says \`$module\`. Go resolves the module by path: a v$rel_major tag on this go.mod publishes something no consumer of this line can require."
		fi
		# The base branch, not just the tree. A v1 release PR carrying this line's
		# tree but TARGETING main passes every other check here -- same module
		# path, same major -- and would land the compat go.mod on the modern line,
		# with the tag then cut from main. R8 asks for the directive checked
		# "vs the target branch and version"; this is the target-branch half, and
		# it is blocking on a release PR even though the same comparison is only
		# advisory on an ordinary one.
		if [ -z "$branch" ]; then
			note "no base branch in context (local run or a non-PR event), so the target-branch check is skipped; CI runs it on the PR"
		else
			case "$rel_major" in
			1) expected_base="$COMPAT_BRANCH" ;;
			*) expected_base="$MODERN_BRANCH" ;;
			esac
			if [ "$branch" != "$expected_base" ]; then
				fail "release PR for v$release_version targets \`$branch\`, but v$rel_major releases are cut from \`$expected_base\` (docs/release.md, the BASE column). Retarget the PR: merging it here puts this line's go.mod on the wrong branch, and the tag follows the merge commit."
			fi
		fi
		# tag == version.go == CHANGELOG heading. `make version-check` asserts the
		# second half, but nothing in CI runs it -- release-check does, and CI
		# never calls release-check. So it is asserted here, where CI does look.
		# No `if [ -f ]` escape: a release PR that deletes the CHANGELOG would
		# otherwise skip this check silently and still be told everything agrees.
		if [ ! -f CHANGELOG.md ]; then
			fail "release PR for v$release_version but there is no CHANGELOG.md. The release notes are part of the release (docs/release.md step 4), and \`make version-check\` -- which CI does not run -- is the only other thing that would have noticed."
		else
			log_version=$(sed -n 's/^## \[\([0-9][^]]*\)\].*/\1/p' CHANGELOG.md | head -n 1)
			if [ -z "$log_version" ]; then
				fail "release PR for v$release_version but CHANGELOG.md has no released-version heading. Move the [Unreleased] items under ## [$release_version] (docs/release.md step 4)."
			elif [ "$log_version" != "$release_version" ]; then
				fail "release PR for v$release_version but the latest CHANGELOG.md heading is [$log_version]. Tag, version.go, and the CHANGELOG must agree."
			fi
		fi
		if [ "$failed" = "0" ]; then
			note "release PR for v$release_version: base branch, version.go, module path, and CHANGELOG all agree"
		fi
	fi
fi

if [ "$is_tag" = "1" ]; then
	# Detection, not prevention: GitHub has already accepted the ref by the time
	# this runs, and for the compat line a published version cannot be withdrawn.
	# The release-PR block above is the gate; this catches a tag pushed without
	# one, early enough that deleting the ref may still beat the first fetch.
	case "$tag" in
		v*)
			tag_version=${tag#v}
			if ! is_semver "$tag_version"; then
				# No further comparisons: a malformed version has no major to
				# compare and nothing valid to match version.go against.
				fail "tag $tag is not a valid module version. Go resolves versions from tags: it must be vMAJOR.MINOR.PATCH with no leading zeros, an optional -prerelease, and no build metadata. Delete the ref before anything fetches it."
			else
				tag_major=$(semver_major "$tag_version")

				if [ "$tag_major" = "0" ]; then
					fail "tag $tag publishes a v0 version, and no line here does: v1.x comes off \`$COMPAT_BRANCH\` and v2.x off \`$MODERN_BRANCH\` (docs/versioning.md). Delete the ref before anything fetches it."
				fi
				tag_expected_module=$(expected_module_path "$tag_major")
				if [ "$module" != "$tag_expected_module" ]; then
					fail "tag $tag needs module path \`$tag_expected_module\`, but go.mod says \`$module\` (path major v$path_major). Go refuses to resolve that combination, and the tag cannot be moved once pushed -- delete the ref before anything fetches it, then publish a corrected version."
				fi

				# The check that was missing: the tag and version.go must agree.
				# version.go is what the client reports as its User-Agent forever,
				# and the release-PR block ties both to the CHANGELOG heading.
				if [ -z "$version" ]; then
					fail "tag $tag pushed but version.go declares no Version; nothing ties this tag to the code it publishes."
				elif [ "$version" != "$tag_version" ]; then
					fail "tag $tag does not match version.go ($version). The published module would report a version it is not. This should have been caught on the release/$tag PR (docs/release.md step 3)."
				else
					note "tag $tag matches version.go ($version)"
				fi
			fi
			;;
		*) note "tag $tag is not a version tag; skipping the tag checks" ;;
	esac
fi

if [ "$on_compat" = "1" ] && [ -n "$version" ]; then
	case "$version" in
		1.*) : ;;
		# 0.x is tolerated OUTSIDE a tag push: nothing has ever been released, and
		# the release PR (#29) is what sets 1.0.0 -- AGENTS.md keeps version bumps
		# out of feature and chore PRs. On a tag it is not tolerated; the tag
		# comparison above is blocking and would catch v1.0.0 against 0.x.
		0.*) note "version.go is $version; the release PR sets 1.0.0 on this line" ;;
		*) warn "version.go is $version on the compat line, which publishes v1.x only" ;;
	esac
fi

if [ "$failed" != "0" ]; then
	printf 'compat-guard: FAILED\n'
	exit 1
fi
printf 'compat-guard: OK\n'
